name: Build NodeJS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        
    - name: Clean dist directory
      run: |
        if [ -d "nodejs/dist" ]; then
          rm -rf nodejs/dist/
          echo "nodejs/dist directory removed"
        else
          echo "nodejs/dist directory does not exist, skipping removal"
        fi
        
    - name: Run npm build
      working-directory: nodejs
      run: |
        npm i
        npm run build
        
    - name: Commit and push dist changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f nodejs/dist/
        git commit -m "Update build artifacts [skip ci]" || echo "No changes to commit"
        git push
